### ISSUE TITLE
Adding versions to sphinx

### ISSUE THREAD

**Issue by DiamonDinoia** [flatironinstitute/finufft#514]
https://github.com/flatironinstitute/finufft/blob/b3c2be7d5ad3d1fb636307c02b02e814b60348a8/.readthedocs.yaml#L24

this might work:
```yml
# Include all versions by default and manually exclude the unneeded ones
versions:
  only: "master"
  regex: '^v*$'
```
